image: python:3.8

stages:
  - build
  - deploy

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python app.py build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  image: ruby:2.7
  script:
    - gem install gitlab-pages
    - gitlab-pages
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master # You can change this to the branch you want to deploy to GitLab Pages
