image: python:3.9

stages:
  - build
  - deploy
  - nightly

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - rm -rf public
    - mkdir public
    - mkdir public/output
    - python gitlab-review-load.py --output_dir=public/output
    - python to_histogram.py public/output/review_counts.csv --output_dir=public/output
  artifacts:
    paths:
      - public/output/

pages:
  stage: deploy
  script:
    - mv index.html public/
    - mv styles.css public/
    - mv scripts.js public/
  artifacts:
    paths:
      - public
  only:
    - master

rebuild:
  stage: nightly
  script:
    - echo "Rebuilding and repushing nightly"
  only:
    - schedules
