image: python:3.9

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python gitlab-review-load.py --output_dir=public/output
    - python to_histogram.py public/output/review_counts.csv --output_dir=public/output
  artifacts:
    paths:
      - public/output/

pages:
  stage: deploy
  script:
    - mv public public_old
    - mkdir public
    - mv public_old/* public/
    - mv index.html public/
    - mv styles.css public/
    - mv scripts.js public/
  artifacts:
    paths:
      - public
  only:
    - master

